version: "3.3"

services:
  postgresql:
    image: postgres:13.1
    container_name: "microservices-demo-postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-service
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'microservices-demo-rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"